#!/usr/bin/env node
/**
 * buildplace — turn the Luau sources into a publishable .rbxlx place file.
 *
 * This exists so the whole pipeline works without Studio in the loop: sources
 * in git → place file → `bot publish` → live. Studio is still the nicer way to
 * *author* a place (and the plugin syncs into it), but a build that can only
 * be produced by a human clicking Save As is not a build.
 *
 *     node roblox/tools/buildplace.mjs          # or: npm run roblox:place
 *
 * Output: roblox/build/BLACKROOT.rbxlx
 *
 * .rbxlx is Roblox's XML place format. Everything the game needs at runtime is
 * a script, and the world itself is generated by WorldBuilder when the server
 * starts, so the place file is small — a handful of services and the source
 * tree. That is deliberate: a procedural world means the place file never
 * becomes the thing you have to diff.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildTree } from './syncserver.mjs';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, '..');
const OUT_DIR = path.join(ROOT, 'build');
const OUT = path.join(OUT_DIR, 'BLACKROOT.rbxlx');
const MODEL_OUT = path.join(OUT_DIR, 'BLACKROOT-scripts.rbxmx');

let referent = 0;
const ref = () => `RBX${referent++}`;

const esc = (s) =>
  String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

/** A CDATA block that survives source containing the sequence "]]>". */
function cdata(source) {
  return `<![CDATA[${String(source).split(']]>').join(']]]]><![CDATA[>')}]]>`;
}

function scriptItem(node, indent) {
  const pad = ' '.repeat(indent);
  const lines = [];
  lines.push(`${pad}<Item class="${node.className}" referent="${ref()}">`);
  lines.push(`${pad}  <Properties>`);
  lines.push(`${pad}    <string name="Name">${esc(node.name)}</string>`);
  if (node.className !== 'Folder') {
    lines.push(`${pad}    <ProtectedString name="Source">${cdata(node.source || '')}</ProtectedString>`);
    lines.push(`${pad}    <bool name="Enabled">true</bool>`);
  }
  lines.push(`${pad}  </Properties>`);
  for (const child of node.children || []) {
    lines.push(scriptItem(child, indent + 2));
  }
  lines.push(`${pad}</Item>`);
  return lines.join('\n');
}

function service(className, indent, body = '', extraProps = '') {
  const pad = ' '.repeat(indent);
  return [
    `${pad}<Item class="${className}" referent="${ref()}">`,
    `${pad}  <Properties>`,
    `${pad}    <string name="Name">${className}</string>`,
    extraProps,
    `${pad}  </Properties>`,
    body,
    `${pad}</Item>`,
  ]
    .filter(Boolean)
    .join('\n');
}

function build() {
  const tree = buildTree();

  const byTarget = {};
  for (const root of tree.roots) byTarget[root.target] = root;

  const serverBody = byTarget.ServerScriptService ? scriptItem(byTarget.ServerScriptService.tree, 4) : '';
  const sharedBody = byTarget.ReplicatedStorage ? scriptItem(byTarget.ReplicatedStorage.tree, 4) : '';
  const clientChildren = byTarget.StarterPlayerScripts
    ? (byTarget.StarterPlayerScripts.tree.children || []).map((c) => scriptItem(c, 6)).join('\n')
    : '';

  const lighting = `    <Color3 name="Ambient"><R>0.19</R><G>0.2</G><B>0.23</B></Color3>
    <Color3 name="OutdoorAmbient"><R>0.36</R><G>0.38</G><B>0.42</B></Color3>
    <float name="Brightness">2.4</float>
    <float name="ClockTime">7.2</float>
    <bool name="GlobalShadows">true</bool>
    <float name="FogStart">120</float>
    <float name="FogEnd">900</float>
    <token name="Technology">2</token>`;

  const starterPlayer = service(
    'StarterPlayer',
    2,
    [
      '    <Item class="StarterPlayerScripts" referent="' + ref() + '">',
      '      <Properties>',
      '        <string name="Name">StarterPlayerScripts</string>',
      '      </Properties>',
      clientChildren,
      '    </Item>',
    ]
      .filter(Boolean)
      .join('\n'),
  );

  const xml = `<?xml version="1.0" encoding="utf-8"?>
<roblox xmlns:xmime="http://www.w3.org/2005/05/xmlmime" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.roblox.com/roblox.xsd" version="4">
${service('Workspace', 2, '', '    <bool name="FilteringEnabled">true</bool>\n    <bool name="StreamingEnabled">true</bool>')}
${service('Lighting', 2, '', lighting)}
${service('ReplicatedStorage', 2, sharedBody)}
${service('ServerScriptService', 2, serverBody)}
${service('ServerStorage', 2)}
${starterPlayer}
${service('SoundService', 2, '', '    <bool name="RespectFilteringEnabled">true</bool>')}
${service('Players', 2, '', '    <bool name="CharacterAutoLoads">true</bool>\n    <float name="RespawnTime">4</float>')}
${service('Teams', 2)}
${service('Chat', 2)}
</roblox>
`;

  fs.mkdirSync(OUT_DIR, { recursive: true });
  fs.writeFileSync(OUT, xml);

  const model = buildModel(tree);
  fs.writeFileSync(MODEL_OUT, model);

  return { xml, model, tree };
}

/**
 * The same scripts as a .rbxmx *model* rather than a whole place.
 *
 * Use this when you already have a place you care about and do not want to
 * replace it: right-click a service in the Explorer → Insert from File → pick
 * this, and a BLACKROOT folder appears holding three labelled folders. Drag
 * each one where its name says. It is three drags, and it leaves everything
 * else in your place alone — which opening the .rbxlx would not.
 */
function buildModel(tree) {
  const byTarget = {};
  for (const root of tree.roots) byTarget[root.target] = root;

  const bucket = (name, note, children, indent) => {
    const pad = ' '.repeat(indent);
    return [
      `${pad}<Item class="Folder" referent="${ref()}">`,
      `${pad}  <Properties>`,
      `${pad}    <string name="Name">${esc(name)}</string>`,
      `${pad}  </Properties>`,
      `${pad}  <Item class="StringValue" referent="${ref()}">`,
      `${pad}    <Properties>`,
      `${pad}      <string name="Name">WHERE_THIS_GOES</string>`,
      `${pad}      <string name="Value">${esc(note)}</string>`,
      `${pad}    </Properties>`,
      `${pad}  </Item>`,
      children,
      `${pad}</Item>`,
    ]
      .filter(Boolean)
      .join('\n');
  };

  const serverBucket = bucket(
    '1_DRAG_INTO_ServerScriptService',
    'Drag the Blackroot script inside this folder into ServerScriptService.',
    byTarget.ServerScriptService ? scriptItem(byTarget.ServerScriptService.tree, 6) : '',
    4,
  );
  const sharedBucket = bucket(
    '2_DRAG_INTO_ReplicatedStorage',
    'Drag the Shared folder inside this folder into ReplicatedStorage.',
    byTarget.ReplicatedStorage ? scriptItem(byTarget.ReplicatedStorage.tree, 6) : '',
    4,
  );
  const clientBucket = bucket(
    '3_DRAG_INTO_StarterPlayerScripts',
    'Drag all three scripts inside this folder into StarterPlayer > StarterPlayerScripts.',
    byTarget.StarterPlayerScripts
      ? (byTarget.StarterPlayerScripts.tree.children || []).map((c) => scriptItem(c, 6)).join('\n')
      : '',
    4,
  );

  return `<?xml version="1.0" encoding="utf-8"?>
<roblox xmlns:xmime="http://www.w3.org/2005/05/xmlmime" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.roblox.com/roblox.xsd" version="4">
  <Item class="Folder" referent="${ref()}">
    <Properties>
      <string name="Name">BLACKROOT</string>
    </Properties>
${serverBucket}
${sharedBucket}
${clientBucket}
  </Item>
</roblox>
`;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const { xml, tree } = build();
  let scripts = 0;
  const tally = (n) => {
    if (n.className !== 'Folder') scripts++;
    (n.children || []).forEach(tally);
  };
  tree.roots.forEach((r) => tally(r.tree));
  console.log(`✓ ${path.relative(process.cwd(), OUT)}  ${(xml.length / 1024).toFixed(0)} KB, ${scripts} scripts`);
  console.log(`  a whole place — File → Open in Studio, or: npm run roblox:bot -- publish`);
  console.log(`✓ ${path.relative(process.cwd(), MODEL_OUT)}`);
  console.log(`  just the scripts — right-click a service → Insert from File, into a place you already have`);
}

export { build, OUT, MODEL_OUT, cdata };
